config/routes.rb
T::Application.routes.draw do

  get "home/index"

  resources :clients

  resources :pizzas

  resources :users

root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base


def self.search(search)
  search_condition = "%" + search + "%"
  find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
end



end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    @client = Client.search params[:search]
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.destroy
        format.html { redirect_to clients_url, notice: 'Client was successfully deleted' }
        format.json { head :ok }
      else
        format.html { redirect_to clients_url, notice: 'Problem: Client NOT deleted !' }
      end
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pizzas }
    end
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
    @pizza = Pizza.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/new
  # GET /pizzas/new.json
  def new
    @pizza = Pizza.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pizza }
    end
  end

  # GET /pizzas/1/edit
  def edit
    @pizza = Pizza.find(params[:id])
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(params[:pizza])

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render json: @pizza, status: :created, location: @pizza }
      else
        format.html { render action: "new" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pizzas/1
  # PUT /pizzas/1.json
  def update
    @pizza = Pizza.find(params[:id])

    respond_to do |format|
      if @pizza.update_attributes(params[:pizza])
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy

    respond_to do |format|
      format.html { redirect_to pizzas_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<%= javascript_include_tag "jquery.maskedinput" %>

<script type="text/javascript">

jQuery(function($){
   $(".phone").mask("(99) 9999-9999");
});

</script>


<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <table>
      <tr>
        <th>
             <div class="field">
                <%= f.label :name %>
                <%= f.text_field :name %>
             </div>
        </th>
        <th>
          <div class="field">
              <%= f.label :phone %>
                <%= f.text_field :phone , :class => 'phone' %>
              </div>
        </th>
      </tr>
      <tr>
            <th>
                    <div class="field">
                        <%= f.label :address %>
                        <%= f.text_field :address %>
                    </div>
            </th>
            <th>
                    <div class="field">
                        <%= f.label :number %>
                        <%= f.number_field :number %>
                    </div>
                  <div class="field">
                    <%= f.label :complement %>
                    <%= f.text_field :complement %>
                  </div>
            </th>

      </tr>
      <tr>
        <th>
           <div class="field">
                <%= f.label :mail %>
                <%= f.text_field :mail %>
            </div>
        </th>
      </tr>
    </table>

    <br>

<nav id="menu" class="clearfix" role="navigation">
  <%= f.submit %>
  <%= link_to 'Back', clients_path %>
</nav>
<% end %>

app/views/clients/_search.html.erb
<% form_tag :controller => 'clients', :action => 'search', :method => 'get' do %>
      <%= text_field_tag :search, params[:search], :id => 'search_field' %>
      <%= submit_tag "Search", :name => nil %>
      <%= link_to_function "Clear", "$('search_field').clear()" %>
 <% end %>

app/views/clients/_search_results.html.erb
  <ul>
    <% @clients.each do |grant| %>
  <li><%= link_to clients.name,
    :action => 'show', :id => clients.id  %></li>
  <% end %>
  </ul>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<script>

  $(document).ready(function(){
   setTimeout(function(){
  $("#messageBox").fadeOut("slow", function () {
  $("#messageBox").remove();
      });

}, 2000);
 });
</script>

<h1>Clients</h1>

<% if notice %>
	<p id="messageBox">
		<a class="spch-bub-inside">
			<span class="point"></span>  
			<em><%= notice %></em>
		</a>
	</p>
<% end %>
<table>
  <tr>
    <th>Phone</th>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
     <td><%= client.phone %></td>
    <td><%= client.name %></td>
    <td><center><%= link_to image_tag("edit.png"), edit_client_path(client) %></center></td>
    <td><center><%= link_to image_tag("delete.png"), client, confirm: 'Are you sure?', method: :delete %></center></td>
  </tr>
<% end %>
</table>

<br />

<nav id="menu" class="clearfix" role="navigation">
<%= link_to 'New Client', new_client_path %>
</nav>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

app/views/clients/search.html.erb
<h1>Search</h1>

<%= render :partial => 'clients/search' %>

app/views/clients/show.html.erb
<script>

  $(document).ready(function(){
   setTimeout(function(){
  $("#messageBox").fadeOut("slow", function () {
  $("#messageBox").remove();
      });

}, 2000);
 });
</script>

<% if notice %>
	<p id="messageBox">
		<a class="spch-bub-inside">
			<span class="point"></span>  
			<em><%= notice %></em>
		</a>
	</p>
<% end %>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Address:</b>
  <%= @client.address %>
</p>

<p>
  <b>Number:</b>
  <%= @client.number %>
</p>

<p>
  <b>Complement:</b>
  <%= @client.complement %>
</p>

<p>
  <b>Mail:</b>
  <%= @client.mail %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>

    <meta charset="utf-8" />

  <%= stylesheet_link_tag "style" %>
<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %> 

    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title></title>

    <meta name="description" content="" />
    
     <!-- Mobile viewport optimized: j.mp/bplateviewport -->
 	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <!--<link href="style.css" rel="stylesheet" /> -->
    <!--<link href="http://fonts.googleapis.com/css?family=Droid+Serif:regular,bold" rel="stylesheet" />  Load Droid Serif from Google Fonts -->
    
    <!-- All JavaScript at the bottom, except for Modernizr and Respond.
    	Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries -->
    <!--<script src="javascripts/modernizr-1.7.min.js"></script>-->

  <%= javascript_include_tag "modernizr-1.7.min" %>
  
  <!--<script src="javascripts/respond.min.js"></script>-->

  <%= javascript_include_tag "respond.min.js" %>

</head>

<body>


<div id="wrapper">

   <header id="header" class="clearfix"> 
			
			<hgroup>
				<%= image_tag("pizza.png", :class => "thumbnail alignleft")%>
				<h1 id="site-title"><a href="index.html">OpenPizza</a></h1>
				<h1 id="site-description">FOSS to manage your pizza delivery!</h1>
			</hgroup>
    
   </header> <!-- #header -->

<div id="main" class="clearfix">

	<!-- Navigation -->
    <nav id="menu" class="clearfix" role="navigation">
        <ul> 
           
           
            <li class="current"><%= link_to "Home", root_path %></li>
            
            <li>
                <%= link_to "Clients", clients_path %>
                <ul>
                    <li><%= link_to "New Client", new_client_path %></li>
                </ul>
            </li>
            
            <li>
                <a href="about.html"><b>Orders</b></a>
                <ul>
                    <li><a href="#">New order</a></li>
                    <li><a href="#">Processing</a></li>
                    <li><a href="#">Today's History</a></li>
                    <li><a href="#">Older History</a></li>
                </ul>
            </li>
            
            <li>
                <a href="about.html"><b>Products</b></a>
                <ul>
                    <li><a href="#">My Products</a></li>
                    <li><a href="#">Search</a></li>
                    <li><a href="#">New Products</a></li>
                    <li><a href="#">Stock</a></li>
                </ul>
            </li>
            
            <li>
                <a href="about.html"><b>Statistics</b></a>
                <ul>
                    <li><a href="#">Top Clients</a></li>
                    <li><a href="#">Top Pizzas</a></li>
                    <li><a href="#">Top hours</a></li>
                </ul>
            </li>
                    
            <li><a href="contact.html"><b>Settings</b></a></li>
            
            <li><a href="contact.html"><b>Support</b></a></li>
        </ul>
    </nav> <!-- #nav -->
    
    
    
    
    <!-- Show a "Please Upgrade" box to both IE7 and IE6 users (Edit to IE 6 if you just want to show it to IE6 users) - jQuery will load the content from js/ie.html into the div -->
    
    <!--[if lte IE 7]>
        <div class="ie warning"></div>
    <![endif]-->
    
    <div id="content" role="main">
   
   <%= yield %> 
        
        
  </div> <!-- #content -->
    
 <!--     <aside id="sidebar" role="complementary">
    
        <aside class="widget">
            <h3>Go to</h3>
            
            <ul>
                <li><a href="#">Active Orders</a></li>
                <li><a href="#">Delivering Orders</a></li>
                <li><a href="#">Clients Wainting</a></li>
            </ul>
        </aside> 
    
    </aside> -->
    
</div> <!-- #main -->
    
    <footer id="footer">
        <!-- You're free to remove the credit link to Jayj.dk in the footer, but please, please leave it there :) -->
        <center><p>
            Copyright &copy; 2011 <a href="#">openpizza.org</a>
            <span class="sep">|</span>
            Design by <a href="http://jayj.dk" title="Design by Jayj.dk">Jayj.dk</a>
        </p></center>
    </footer> <!-- #footer -->
    
    <div class="clear"></div>

</div> <!-- #wrapper -->

	<!-- JavaScript at the bottom for fast page loading -->
	<!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>-->

  <%= javascript_include_tag "jquery.min" %>
   <!-- <script src="javascripts/script.js"></script>-->
  <%= javascript_include_tag "script" %>

</body>
</html>

app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :components %><br />
    <%= f.text_field :components %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<h1>Listing pizzas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Components</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pizzas.each do |pizza| %>
  <tr>
    <td><%= pizza.name %></td>
    <td><%= pizza.components %></td>
    <td><%= link_to 'Show', pizza %></td>
    <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
    <td><%= link_to 'Destroy', pizza, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pizza', new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pizza.name %>
</p>

<p>
  <b>Components:</b>
  <%= @pizza.components %>
</p>


<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>